---
layout: cv
title: Caden DeSpain's Resume
---
# Caden DeSpain
BYU-Idaho Graduate

<div id="webaddress">
<a href="cadendespain@icloud.com">cadendespain@icloud.com</a>
| <a href="https://www.linkedin.com/in/caden-despain-50745920b/">My LinkedIn page</a>
</div>


## Currently

Graduating with a Bachelors of Science in Biology from BYU-Idaho and prepping for masters programs.

### Specialized in

Bioinformatics and Data Science


### Research interests

Genetics, Phylogenetics, Evolution, Epidemiology, Software Developement, De-extinction 


## Education

`August 2020-April 2024`
__Brigham Young University Idaho__

`March 2021`
__Phlebotomy Training Specialists__

`August 2015-May 2019`
__Snowflake High School__



## Work Experience

`July 2023-October 2023`
__Cashier__, Rexburg, Idaho

- Cleaned front end, assisted customers with variety of needs, pushed carts
- Gained great customer service skills, and problem-solving skills

`September 2022-July 2023`
__Parking Service Officer__, Brigham Young University Idaho

- Maintained campus parking rules by patrolling lots and ticketing violators
- Learned to provide good customer service, and how to be polite and patient with difficult people

`April 2021-July 2021`
__Dining Crew Member__, Homestead Assisted Living

- Prepared, cooked, and served elderly patients suffering from dementia and other health problems
- Made sure patients were satisfied with meals, and learned to step up and be a leader when someone more experienced was not around


## Volunteer Experience

`July 2017`
__Eagle Scout__ 

- Conducted, organized, and oversaw construction of new fencing on a section of the Taylor rodeo grounds for total of 130 hours
- Learned how to adapt to new situations

`August 2018-May 2019`
__Link Crew Leader__

- Mentored, and assisted incoming freshman

'August 2022- October 2023'
__Rock Gym Volunteer__

- Taught new climbers about safety and how to use ropes and harnesses to safely climb
- Ensured safety of all climbers on boulder wall and top rope wall 

<!-- ### Footer

Last updated: May 2013 -->

